// Regenerates src/abi.ts from Foundry build artifacts. Run `forge build` in the repo root first.
import { readFileSync, writeFileSync } from "node:fs";

const artifacts = [
  ["vaultAbi", "../out/BursarVault.sol/BursarVault.json"],
  ["tokenAbi", "../out/MockUSDG.sol/MockUSDG.json"],
];
let out = "// Generated by `npm run abi` from Foundry artifacts (../out). Do not edit by hand.\n";
for (const [name, path] of artifacts) {
  const { abi } = JSON.parse(readFileSync(new URL(path, new URL("../", import.meta.url)), "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(new URL("../src/abi.ts", import.meta.url), out);
console.log("wrote src/abi.ts");
