// Regenerates src/abi.ts from Foundry build artifacts (run `forge build` in the repo root first).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const contracts = [
  ["vaultAbi", "BursarVault.sol/BursarVault.json"],
  ["tokenAbi", "MockUSDG.sol/MockUSDG.json"],
] as const;

let out = "// Generated by `npm run abi` from Foundry artifacts. Do not edit by hand.\n";
for (const [name, path] of contracts) {
  const { abi } = JSON.parse(readFileSync(`${root}out/${path}`, "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(fileURLToPath(new URL("./abi.ts", import.meta.url)), out);
console.log("wrote src/abi.ts");
